//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DADOC
    {
        public int Matruyen { get; set; }
        public int Mand { get; set; }
        public Nullable<System.DateTime> Ngaydoc { get; set; }
    
        public virtual TRUYEN TRUYEN { get; set; }
    }
}
