//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloworld.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.LUUTRUs = new HashSet<LUUTRU>();
        }
        
        public int Mand { get; set; }
        [Required]
        public string Hoten { get; set; }
        [Required]
        [Display(Name ="Nội dung phản ánh")]
        public string Taikhoan { get; set; }
       // [Required]
        public string Matkhau { get; set; }
        //[Required]
        //[Compare("Matkhau")]
        public string Nhaplaimk { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Diachi { get; set; }
        [Required]
        public string Dienthoai { get; set; }
        [Required]
        public Nullable<System.DateTime> Ngaysinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUUTRU> LUUTRUs { get; set; }
    }
}
