//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloworld.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TRUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRUYEN()
        {
            this.DADOCs = new HashSet<DADOC>();
            this.LUUTRUs = new HashSet<LUUTRU>();
        }
    
        public int Matruyen { get; set; }
        [Required]
        public string Tentruyen { get; set; }
        [Required]
        public Nullable<int> Matacgia { get; set; }
        [Required]
        public Nullable<int> Maloai { get; set; }
        [Required]
        public Nullable<int> Manxb { get; set; }
        [Required]
        public string Anhbia { get; set; }
        [Required]
        public string Noidung { get; set; }
        [Required]
        public Nullable<int> Sochuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DADOC> DADOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUUTRU> LUUTRUs { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
